model_config: &client
  provider: AzureOpenAIChatCompletionClient
  config:
    model: gpt-4o
    azure_endpoint: "https://trapi.research.microsoft.com/gcr/shared"
    azure_deployment: "gpt-4o_2024-11-20"
    api_version: "2024-10-21"
    azure_ad_token_provider:
      provider: autogen_ext.auth.azure.AzureTokenProvider
      config:
        provider_kind: DefaultAzureCredential
        scopes:
          - api://trapi/.default
    max_retries: 10

orchestrator_client: *client
coder_client: *client
web_surfer_client: *client
file_surfer_client: *client
action_guard_client: *client
user_proxy_client: *client

novnc_endpoint: "4.155.4.13:9801"
playwright_port: 9800
